# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clier < Formula
  desc "Design your agent team. Run them in real terminals, not API calls."
  homepage "https://github.com/jakeraft/clier"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jakeraft/clier/releases/download/v0.1.0/clier_darwin_amd64.tar.gz"
    sha256 "df05f6963423118df96f8b4bc86ba5f7e783add8ae181190de63302baf0b8f3a"

    define_method(:install) do
      bin.install "clier"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jakeraft/clier/releases/download/v0.1.0/clier_darwin_arm64.tar.gz"
    sha256 "43249c5200406db091f31782c3079c890f56f4d7cd58c64e5d9d486450797d46"

    define_method(:install) do
      bin.install "clier"
    end
  end
end
