# This file was generated by GoReleaser. DO NOT EDIT.
cask "clier" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "dc75c4f702c1cce94cbb711d9cc7e2d10cff9eb504a474fc24b74f995698758e"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_amd64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
    on_arm do
      sha256 "6ca63685dfe4ca9f0b9df400ea8a8f87e5f9e68b6938acc7797efded2175933b"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_arm64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
  end

  name "clier"
  desc "Harness multi-agent teams with a native CLI."
  homepage "https://github.com/jakeraft/clier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "clier"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clier"]
    end
  end

  # No zap stanza required

end
