# This file was generated by GoReleaser. DO NOT EDIT.
cask "clier" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "0396f160c4eb8132cb550308071db55f8271d6534edb3c0deeafe8fa828e9816"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_amd64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
    on_arm do
      sha256 "83b8b816b2785c7f88758a98fc02bd1baddf7de9477698d312bb33d93557f441"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_arm64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
  end

  name "clier"
  desc "Harness multi-agent teams with a native CLI."
  homepage "https://github.com/jakeraft/clier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "clier"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clier"]
    end
  end

  # No zap stanza required

end
