# This file was generated by GoReleaser. DO NOT EDIT.
cask "clier" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "d9ad01a27339d9cd3662e84658adec5c805dab1fd40359a0574b5404a5fb93f1"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_amd64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
    on_arm do
      sha256 "6ffc2c667d1785b51d57b4d3bf559f45cda527fb86ab1ecbbcb48118c87cdff5"
      url "https://github.com/jakeraft/clier/releases/download/v#{version}/clier_darwin_arm64.tar.gz",
        verified: "github.com/jakeraft/clier"
    end
  end

  name "clier"
  desc "Harness multi-agent teams with a native CLI."
  homepage "https://github.com/jakeraft/clier"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "clier"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clier"]
    end
  end

  # No zap stanza required

end
